Push api key validator
appsignal/appsignal-python pull request #103
Opened 2023-07-07 14:25 UTC by jeffkreeftmeijer

Currently, validating push API keys is done in the install command. The
upcoming diagnose command also needs to validate push API keys, so this
patch moves the code into a separate module that will be used from both
places.

[skip changeset]

2023-07-10 09:22 UTC, luismiramirez commented
I moved the module to the CLI namespace.

2023-07-10 14:02 UTC, unflxw approved these changes

2023-07-17 07:44 UTC, tombruijn requested changes
Build is red.

2023-07-17 08:42 UTC, luismiramirez commented
@tombruijn this is working on the diagnose command PR. Closing this one

2023-07-17 08:42 UTC, closed without merging